# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!


target 'IOS8SwiftCocoapodsTutorial' do
pod 'FontBlaster'
end

target 'IOS8SwiftCocoapodsTutorialTests' do

end

